### ISSUE TITLE
Import example

### ISSUE THREAD

**Issue by jimmiebtlr** [vazco/meteor-universe-react-carousel#1]
Could you provide an example of how to import this?  The example file listed seems to show use, but not importing in a meteor application.

**Comment by aaronsmulktis** [comment]
+1 for a meteor import/include/require example.. I've been playing around with npmRequire, still no luck..

Thanks in advance!

**Comment by arrygoo** [comment]
+1, anyone had luck the require error?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
