### ISSUE TITLE
Failed to install on Meteor 1.4

### ISSUE THREAD

**Issue by maitrid** [vazco/meteor-universe-react-carousel#2]
I'm not sure whether this is Meteor 1.4 specific. But when I tried to install using  `meteor add universe:carousel`, I got this:

```
MINISAT-out: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
MINISAT-err: Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.
```

And that's followed by a long stack trace. Any clue?

Thanks!

**Comment by MacRusher** [comment]
If you're using Meteor >= 1.3 then you probably want to use original package from npm instead: https://github.com/akiran/react-slick

I guess that the error you've pasted is also a part of a bigger problem, not very likely to be related to this package anyway.

**Comment by vfonic** [comment]
The original package doesn't seem to work with meteor either. At least I can't get it to work. Anyone had success?

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
